## Single Neuron with ReLU Activation ##

In neural networks, a single neuron is a fundamental building block that performs a linear transformation followed by an activation function. The linear transformation involves multiplying the input features by corresponding weights and adding a bias term. The activation function introduces non-linearity to the neuron's output, enabling it to learn complex patterns in the data.
1. **Input Layer**:
   - The input layer represents the input features to the neuron. It's typically represented as a row vector where each element corresponds to an input feature:
     $$
     \text{Input Layer} = \begin{bmatrix}
     x_1 & x_2 & \cdots & x_n
     \end{bmatrix}
     $$
   - Here, $$ x_1, x_2, \ldots, x_n $$ represent the individual input features.

In [1]:
import torch
import torch.nn as nn

# Define input tensor (1 sample, 4 features)
x = torch.tensor([[1.0, 2.0, 3.0, 4.0]])
x

tensor([[1., 2., 3., 4.]])

2. **Weights**:
   - Weights are the parameters of the neuron that are learned during the training process. Each weight corresponds to a connection between an input feature and the neuron.
   - Weights are typically represented as a column vector:
     $$
     \text{Weights} = \begin{bmatrix}
     w_1 \\
     w_2 \\
     \vdots \\
     w_n
     \end{bmatrix}
     $$
   - Here, $$ w_1, w_2, \ldots, w_n $$ represent the individual weights.

In [2]:
# Weights 
weights = torch.tensor([[0.1], [0.2], [0.3], [0.4]])
weights

tensor([[0.1000],
        [0.2000],
        [0.3000],
        [0.4000]])

3. **Bias**:
   - The bias term is another parameter of the neuron. It's added to the weighted sum of inputs to shift the activation function.
   - The bias is represented as a scalar value:
     $$
     \text{Bias} = b
     $$

In [3]:
# Bias
bias = torch.tensor([0.5])
bias

tensor([0.5000])

4. **Linear Transformation**:
   - This represents the result of the linear transformation of the input by the neuron, including the weighted sum of inputs and the bias term.
   - It's computed by multiplying the input layer by the weights and then adding the bias term:
     $$
     \text{Linear Output} = \begin{bmatrix}
     x_1w_1 + x_2w_2 + \cdots + x_nw_n + b
     \end{bmatrix}
     $$

In [4]:
# Linear transformation (input layer -> neuron)
linear_output = torch.matmul(x, weights) + bias
linear_output

tensor([[3.5000]])

5. **ReLU Activation**:
   - ReLU (Rectified Linear Unit) is an activation function commonly used in neural networks to introduce non-linearity.
   - It applies an element-wise operation to the output of Step 1, replacing any negative values with zero:
     $$
     \text{ReLU}(\text{Linear Output}) = \begin{bmatrix}
     \max(0, x_1w_1 + x_2w_2 + \cdots + x_nw_n + b)
     \end{bmatrix}
     $$
   - This ensures that the output of the neuron is always non-negative.

In [5]:
# ReLU activation
relu_output = nn.functional.relu(linear_output)

# Output
print("ReLU output:", relu_output)

ReLU output: tensor([[3.5000]])
