In [ ]:
!pip install datasets
!pip install transformers
!pip install asrecognition
!pip install jiwer

     |████████████████████████████████| 50 kB 3.1 MB/s 
  Created wheel for python-Levenshtein: filename=python_Levenshtein-0.12.2-cp37-cp37m-linux_x86_64.whl size=149857 sha256=64610d689404e662e4d58cdfa599f37fe105d670d499cdd2e2f195393db0d837
  Stored in directory: /root/.cache/pip/wheels/05/5f/ca/7c4367734892581bb5ff896f15027a932c551080b2abd3e00d
Successfully built python-Levenshtein


In [ ]:
from datasets import load_metric

In [ ]:
from asrecognition import ASREngine
import os

In [ ]:
metric = load_metric("wer")

In [ ]:
List_Label=[]
with open("labels.txt") as k:
    for line in k:
        List_Label.append(line[:-1].lower())
List_Label

['he hoped there would be stew for dinner turnips and carrots and bruised potatoes and fat mutton pieces to be ladled out in thick peppered flour fattened sauce',
 'stuff it into you his belly counselled him',
 'after early nightfall the yellow lamps would light up here and there the squalid quarter of the brothels',
 'hello bertie any good in your mind',
 'number ten fresh nelly is waiting on you good night husband',
 "the music came nearer and he recalled the words the words of shelley's fragment upon the moon wandering companionless pale for weariness",
 'the dull light fell more faintly upon the page whereon another equation began to unfold itself slowly and to spread abroad its widening tail',
 'a cold lucid indifference reigned in his soul',
 'the chaos in which his ardour extinguished itself was a cold indifferent knowledge of himself',
 'at most by an alms given to a beggar whose blessing he fled from he might hope wearily to win for himself some measure of actual grace',
 'wel

In [ ]:
#Need test data
url="www.openslr.org/resources/12/test-clean.tar.gz"
!wget $url

--2021-12-14 04:03:37--  http://www.openslr.org/resources/12/test-clean.tar.gz
Resolving www.openslr.org (www.openslr.org)... 46.101.158.64
Connecting to www.openslr.org (www.openslr.org)|46.101.158.64|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://us.openslr.org/resources/12/test-clean.tar.gz [following]
--2021-12-14 04:03:37--  https://us.openslr.org/resources/12/test-clean.tar.gz
Resolving us.openslr.org (us.openslr.org)... 46.101.158.64
Connecting to us.openslr.org (us.openslr.org)|46.101.158.64|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 346663984 (331M) [application/x-gzip]
Saving to: ‘test-clean.tar.gz’

test-clean.tar.gz   100%[===================>] 330.60M  27.0MB/s    in 13s     

2021-12-14 04:03:51 (24.6 MB/s) - ‘test-clean.tar.gz’ saved [346663984/346663984]



In [ ]:
!mkdir test_File
!tar -C test_File -xvzf test-clean.tar.gz
dirs=os.listdir("test_File/LibriSpeech/test-clean")
dir=list(sorted(set(dirs)))
print(dir)

LibriSpeech/LICENSE.TXT
LibriSpeech/README.TXT
LibriSpeech/CHAPTERS.TXT
LibriSpeech/SPEAKERS.TXT
LibriSpeech/BOOKS.TXT
LibriSpeech/test-clean/
LibriSpeech/test-clean/6930/
LibriSpeech/test-clean/6930/75918/
LibriSpeech/test-clean/6930/75918/6930-75918-0000.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0007.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0006.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0005.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0004.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0002.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0011.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0015.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0003.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0010.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0001.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0018.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0008.flac
LibriSpeech/test-clean/6930/75918/6930-75918-0017.flac
LibriSpeech/test-clean/

In [ ]:
!mkdir all_test
for i in dir:
  ids=os.listdir("test_File/LibriSpeech/test-clean/"+i)
  for j in ids:
    files=os.listdir("test_File/LibriSpeech/test-clean/"+i+"/"+j)
    os.system("mv test_File/LibriSpeech/test-clean/"+i+"/"+j+"/*.flac all_test")

In [ ]:
dirs=os.listdir("all_test")
dirs=sorted(dirs)

In [ ]:
paths=[]
for i in dirs:
    paths.append("all_test/"+i)
paths

['all_test/1089-134686-0000.flac',
 'all_test/1089-134686-0001.flac',
 'all_test/1089-134686-0002.flac',
 'all_test/1089-134686-0003.flac',
 'all_test/1089-134686-0004.flac',
 'all_test/1089-134686-0005.flac',
 'all_test/1089-134686-0006.flac',
 'all_test/1089-134686-0007.flac',
 'all_test/1089-134686-0008.flac',
 'all_test/1089-134686-0009.flac',
 'all_test/1089-134686-0010.flac',
 'all_test/1089-134686-0011.flac',
 'all_test/1089-134686-0012.flac',
 'all_test/1089-134686-0013.flac',
 'all_test/1089-134686-0014.flac',
 'all_test/1089-134686-0015.flac',
 'all_test/1089-134686-0016.flac',
 'all_test/1089-134686-0017.flac',
 'all_test/1089-134686-0018.flac',
 'all_test/1089-134686-0019.flac',
 'all_test/1089-134686-0020.flac',
 'all_test/1089-134686-0021.flac',
 'all_test/1089-134686-0022.flac',
 'all_test/1089-134686-0023.flac',
 'all_test/1089-134686-0024.flac',
 'all_test/1089-134686-0025.flac',
 'all_test/1089-134686-0026.flac',
 'all_test/1089-134686-0027.flac',
 'all_test/1089-1346

In [ ]:
asr = ASREngine("en", model_path="jonatasgrosman/wav2vec2-large-xlsr-53-english")
audio_paths = paths[:10]
transcriptions = asr.transcribe(audio_paths)

Downloading:   0%|          | 0.00/214 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/300 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py:349: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  "Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 "


Downloading:   0%|          | 0.00/1.18G [00:00<?, ?B/s]

In [ ]:
print(transcriptions[0]['transcription'])

HE HOPED THERE WOULD BE STO FOR DINNER TURNIPS AND CARRATS AND BRUSED POTATOES AND FAT MUTTON PIECES TO BE LAIDLED OUT IN THICK PEPPERED FLOWER FATTENED SAUCE


In [ ]:
pred=[]
for i in transcriptions:
  pred.append(i['transcription'])

In [ ]:
for i in range(len(pred)):
  pred[i]=pred[i].lower()
pred

['he hoped there would be sto for dinner turnips and carrats and brused potatoes and fat mutton pieces to be laidled out in thick peppered flower fattened sauce',
 'stuff it into you his belly counseled him',
 'after early nightfall the yellow lamps would light up here and there the squallid quarter of the brothels h',
 'hello bertie any good in your mind',
 'number ten fresh nellie is waiting on you goodnight husband',
 "the music came nearer and he recalled the words the words of shelly's fragment upon the moon wandering companionless pale for weariness",
 'the dull light fell more faintly upon the page whereon another equation began to unfold itself slowly and to spread abroad its widening tail',
 'a cold loocid indifference rained in his soul',
 'the chaos in which his ardor extinguished itself was a cold indifferent knowledge of himself',
 'at most by an alms given to a beggar whose blessing he fled from he might hope wearily to win for himself some measure of actual grace']

In [ ]:
metric.compute(predictions=pred,references=List_Label[:10])

0.08928571428571429

In [ ]:
import soundfile as sf
import torch
import numpy as np
import librosa
from datasets import load_dataset
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor, Wav2Vec2Model
# load pretrained model
#The facebook model will not work because there is no processor
#processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-large-xlsr-53")
processor = Wav2Vec2Processor.from_pretrained("jonatasgrosman/wav2vec2-large-xlsr-53-english")
model = Wav2Vec2ForCTC.from_pretrained("jonatasgrosman/wav2vec2-large-xlsr-53-english")
#model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-large-xlsr-53")

Downloading:   0%|          | 0.00/214 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/300 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py:349: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  "Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 "


Downloading:   0%|          | 0.00/1.18G [00:00<?, ?B/s]

In [ ]:
datasets=load_dataset('librispeech_asr','clean')

Downloading:   0%|          | 0.00/2.41k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.82k [00:00<?, ?B/s]

  0%|          | 0/4 [00:00<?, ?it/s]

Downloading:   0%|          | 0.00/338M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/347M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/6.39G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/23.0G [00:00<?, ?B/s]

0 examples [00:00, ? examples/s]

0 examples [00:00, ? examples/s]

0 examples [00:00, ? examples/s]

0 examples [00:00, ? examples/s]

Dataset librispeech_asr downloaded and prepared to /root/.cache/huggingface/datasets/librispeech_asr/clean/2.1.0/f4f37a3069fb71dc8d2984a4647ed7e0ff909bc9f0f9a183550cbc4e2db847ed. Subsequent calls will reuse this data.


  0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
datasets

DatasetDict({
    train.100: Dataset({
        features: ['file', 'audio', 'text', 'speaker_id', 'chapter_id', 'id'],
        num_rows: 28539
    })
    train.360: Dataset({
        features: ['file', 'audio', 'text', 'speaker_id', 'chapter_id', 'id'],
        num_rows: 104014
    })
    validation: Dataset({
        features: ['file', 'audio', 'text', 'speaker_id', 'chapter_id', 'id'],
        num_rows: 2703
    })
    test: Dataset({
        features: ['file', 'audio', 'text', 'speaker_id', 'chapter_id', 'id'],
        num_rows: 2620
    })
})

In [ ]:
test_aud=datasets["test"]["audio"]
test_fil=datasets["test"]["text"]

In [ ]:
audio_sig=[]
for i in test_aud:
  audio_sig.append(i['array'])
audio_sig=np.array(audio_sig)
audio_sig

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  after removing the cwd from sys.path.


array([array([-6.10351562e-05,  9.15527344e-05,  1.06811523e-03, ...,
       -2.19726562e-03, -1.13830566e-02, -8.81958008e-03]),
       array([-0.00570679, -0.00732422,  0.00512695, ...,  0.00085449,
        0.0007019 ,  0.00067139]),
       array([ 0.00091553,  0.00115967,  0.0010376 , ...,  0.00531006,
       -0.00634766, -0.00198364]),
       ...,
       array([6.10351562e-05, 3.05175781e-05, 3.05175781e-05, ...,
       2.74658203e-04, 2.74658203e-04, 2.44140625e-04]),
       array([ 0.00024414,  0.00027466,  0.00024414, ..., -0.00021362,
       -0.00021362, -0.00021362]),
       array([ 6.10351562e-05,  3.05175781e-05,  3.05175781e-05, ...,
       -4.27246094e-04, -3.96728516e-04, -4.27246094e-04])], dtype=object)

In [ ]:
test_aud[0]

{'array': array([-6.10351562e-05,  9.15527344e-05,  1.06811523e-03, ...,
        -2.19726562e-03, -1.13830566e-02, -8.81958008e-03]),
 'path': '6930-75918-0000.flac',
 'sampling_rate': 16000}

In [ ]:
files=audio_sig[:100]
a_file = open("audio_out.txt", "w")
for row in files:
    np.savetxt(a_file, row)

a_file.close()

In [ ]:
len(test_aud[0]['array'])

56080

In [ ]:
!mkdir test_Flac

In [ ]:
!tar -C test_Flac -xvzf test-clean.tar.gz

In [ ]:
predicted_sentences=[]
for i in range(0,10):
  inputs = processor(audio_sig[i], sampling_rate=16000, return_tensors="pt")
  with torch.no_grad():
    logits = model(inputs.input_values).logits
  predicted_ids = torch.argmax(logits, dim=-1)
  predicted_sentence = processor.batch_decode(predicted_ids)
  print(predicted_sentence)
  predicted_sentences.append(predicted_sentence)
  #predicted_ids = torch.argmax(logits, dim=-1)
  #predicted_sentences = processor.batch_decode(predicted_ids)
  #print(predicted_sentences)

['CONCORD RETURNED TO ITS PLACE AMIDST THE TENTS']
['THE ENGLISH FODED TO THE FRENCH BASKETS OF FLOWERS OF WHICH THEY HAD MADE A PLENTIFUL PROVISION TO GREET THE ARRIVAL OF THE YOUNG PRINCESS THE FRENCH IN RETURN INVITED THE ENGLISH TO A SUPPER WHICH WAS TO BE GIVEN THE NEXT DAY']
['CONGRATULATIONS WERE POURED IN UPON THE PRINCESS EVERYWHERE DURING HER JOURNEY']
['FROM THE RESPECT PAID HER ON ALL SINES SHE SEEMED LIKE A QUEEN AND FROM THE ADORATION WITH WHICH SHE WAS TREATED BY TWO OR THREE SHE APPEARED AN OBJECT OF WORSHIPTHE QUEENMOTHER GAVE THE FRENCH THE MOST AFFECTIONATE RECEPTION FRANCE WAS HER NATIVE COUNTRY AND SHE HAD SUFFERED TOO MUCH UNHAPPINESS IN ENGLAND FOR ENGLAND TO HAVE MADE HER FORGET FRANCE']
['SHE TAUGHT HER DAUGHTER THEN BY HER OWN AFFECTION FOR IT THAT LOVE FOR A COUNTRY WHERE THEY HAD BOTH BEEN HOSPITABLY RECEIVED AND WER A BRILLIANT FUTURE OPEN FOR THEM']
['THE COUNT HAD THROWN HIMSELF BACK ON HIS SEAT LEANING HIS SHOULDERS AGAINST THE PARTITION OF THE TENT AND 

In [ ]:
full_pred_sentences=[]
for i in range(0,2620):
  inputs = processor(audio_sig[i], sampling_rate=16000, return_tensors="pt")
  with torch.no_grad():
    logits = model(inputs.input_values).logits
  predicted_ids = torch.argmax(logits, dim=-1)
  predicted_sentence = processor.batch_decode(predicted_ids)
  print(predicted_sentence)
  full_pred_sentences.append(predicted_sentence)

['CONCORD RETURNED TO ITS PLACE AMIDST THE TENTS']
['THE ENGLISH FODED TO THE FRENCH BASKETS OF FLOWERS OF WHICH THEY HAD MADE A PLENTIFUL PROVISION TO GREET THE ARRIVAL OF THE YOUNG PRINCESS THE FRENCH IN RETURN INVITED THE ENGLISH TO A SUPPER WHICH WAS TO BE GIVEN THE NEXT DAY']
['CONGRATULATIONS WERE POURED IN UPON THE PRINCESS EVERYWHERE DURING HER JOURNEY']
['FROM THE RESPECT PAID HER ON ALL SINES SHE SEEMED LIKE A QUEEN AND FROM THE ADORATION WITH WHICH SHE WAS TREATED BY TWO OR THREE SHE APPEARED AN OBJECT OF WORSHIPTHE QUEENMOTHER GAVE THE FRENCH THE MOST AFFECTIONATE RECEPTION FRANCE WAS HER NATIVE COUNTRY AND SHE HAD SUFFERED TOO MUCH UNHAPPINESS IN ENGLAND FOR ENGLAND TO HAVE MADE HER FORGET FRANCE']
['SHE TAUGHT HER DAUGHTER THEN BY HER OWN AFFECTION FOR IT THAT LOVE FOR A COUNTRY WHERE THEY HAD BOTH BEEN HOSPITABLY RECEIVED AND WER A BRILLIANT FUTURE OPEN FOR THEM']
['THE COUNT HAD THROWN HIMSELF BACK ON HIS SEAT LEANING HIS SHOULDERS AGAINST THE PARTITION OF THE TENT AND 

In [ ]:
test_fil

['CONCORD RETURNED TO ITS PLACE AMIDST THE TENTS',
 'THE ENGLISH FORWARDED TO THE FRENCH BASKETS OF FLOWERS OF WHICH THEY HAD MADE A PLENTIFUL PROVISION TO GREET THE ARRIVAL OF THE YOUNG PRINCESS THE FRENCH IN RETURN INVITED THE ENGLISH TO A SUPPER WHICH WAS TO BE GIVEN THE NEXT DAY',
 'CONGRATULATIONS WERE POURED IN UPON THE PRINCESS EVERYWHERE DURING HER JOURNEY',
 'FROM THE RESPECT PAID HER ON ALL SIDES SHE SEEMED LIKE A QUEEN AND FROM THE ADORATION WITH WHICH SHE WAS TREATED BY TWO OR THREE SHE APPEARED AN OBJECT OF WORSHIP THE QUEEN MOTHER GAVE THE FRENCH THE MOST AFFECTIONATE RECEPTION FRANCE WAS HER NATIVE COUNTRY AND SHE HAD SUFFERED TOO MUCH UNHAPPINESS IN ENGLAND FOR ENGLAND TO HAVE MADE HER FORGET FRANCE',
 'SHE TAUGHT HER DAUGHTER THEN BY HER OWN AFFECTION FOR IT THAT LOVE FOR A COUNTRY WHERE THEY HAD BOTH BEEN HOSPITABLY RECEIVED AND WHERE A BRILLIANT FUTURE OPENED BEFORE THEM',
 'THE COUNT HAD THROWN HIMSELF BACK ON HIS SEAT LEANING HIS SHOULDERS AGAINST THE PARTITION OF 

In [ ]:
#WER
metric = load_metric("wer")

Downloading:   0%|          | 0.00/1.91k [00:00<?, ?B/s]

In [ ]:
len(test_fil[:10])

10

In [ ]:
len(predicted_sentences)

10

In [ ]:
metric.compute(predictions=predicted_sentences,references=test_fil[:10])

0.12749003984063745

In [ ]:
len(full_pred_sentences)

2620

In [ ]:
metric.compute(predictions=full_pred_sentences,references=test_fil)

0.1654176810712112